package styles

var themeDefault = Theme{
	Version:         ThemeVersion,
	Name:            "default",
	Highlight:       "#7DCFFF",
	Title:           "#FF6600",
	Accent:          "#7D56F4",
	Active:          "#04B575",
	Idle:            "#FBBF24",
	Completed:       "#60A5FA",
	Stale:           "#EF4444",
	Normal:          "#D4D4D4",
	Dim:             "#888888",
	Border:          "#3A3A5A",
	BorderFocus:     "#7DCFFF",
	SearchBorder:    "#2DD4BF",
	Success:         "#10B981",
	TableHeaderBg:   "#1a1a2e",
	ForceBackground: false,
}

var themeDarkSolid = Theme{
	Version:         ThemeVersion,
	Name:            "dark-solid",
	Highlight:       "#7DCFFF",
	Title:           "#FF6600",
	Accent:          "#7D56F4",
	Active:          "#04B575",
	Idle:            "#FBBF24",
	Completed:       "#60A5FA",
	Stale:           "#EF4444",
	Normal:          "#BBBBBB",
	Dim:             "#888888",
	Border:          "#3A3A5A",
	BorderFocus:     "#7DCFFF",
	SearchBorder:    "#2DD4BF",
	Success:         "#10B981",
	Background:      "#0F111A",
	ForceBackground: true,
	TableHeaderBg:   "#1a1a2e",
}

var themeHighContrast = Theme{
	Version:         ThemeVersion,
	Name:            "high-contrast",
	Highlight:       "#00FFFF",
	Title:           "#FF8800",
	Accent:          "#AA66FF",
	Active:          "#00FF00",
	Idle:            "#FFCC00",
	Completed:       "#00AAFF",
	Stale:           "#FF4444",
	Normal:          "#FFFFFF",
	Dim:             "#AAAAAA",
	Border:          "#666666",
	BorderFocus:     "#00FFFF",
	SearchBorder:    "#00FFAA",
	Success:         "#00FF00",
	Background:      "#000000",
	ForceBackground: true,
	TableHeaderBg:   "#1a1a2e",
}

var themeGruvbox = Theme{
	Version:         ThemeVersion,
	Name:            "gruvbox",
	Highlight:       "#D79921",
	Title:           "#FE8019",
	Accent:          "#D3869B",
	Active:          "#B8BB26",
	Idle:            "#FABD2F",
	Completed:       "#83A598",
	Stale:           "#FB4934",
	Normal:          "#EBDBB2",
	Dim:             "#928374",
	Border:          "#504945",
	BorderFocus:     "#D79921",
	SearchBorder:    "#8EC07C",
	Success:         "#B8BB26",
	Background:      "#282828",
	ForceBackground: true,
	TableHeaderBg:   "#3C3836",
}

