package claudefs

import "time"

// SessionStats holds statistics for a Claude Code session.
type SessionStats struct {
	SessionID      string // Session ID
	Lifecycle      SessionLifecycleSnapshot
	CustomTitle    string        // Title generated by Claude
	Model          string        // Model used (e.g. claude-opus-4.6)
	Version        string        // Claude Code version
	GitBranch      string        // Git branch
	StartTime      time.Time     // Start time
	LastActiveTime time.Time     // Last active time
	Duration       time.Duration // Duration

	TurnCount     int            // Turn count (number of user prompts)
	UserMsgCount  int            // User message count
	ToolCallCount int            // Total tool call count
	ToolUsage     map[string]int // Tool name -> count

	InputTokens  int // Input tokens
	OutputTokens int // Output tokens
	CacheTokens  int // Cache tokens

	CompactCount int // Context compaction count
	ErrorCount   int // API error count
}
